### ISSUE TITLE
Add Storage - Mounted Devices not showing up in list?

### ISSUE THREAD

**Issue by HardwareExtreme** [DaVieS007/bhyve-webadmin#36]
Hey is there any specific way that storage devices have to be mounted for BVCP to see them? I am currently trying to add a disk for storage but I cannot add it on the BVCP webpage even though it is mounted on the system and formatted.

The setup I have is a 200GB zvol attached over iSCSI, formatted as UFS on the BVCP system, I mounted it under /mnt/iscsi-storage1 and /media/iscsi-storage1 but neither show up as being able to add it as storage for BVCP.

**Comment by DaVieS007** [comment]
Allow me some more time to reproduce and fix this issue.

**Comment by DaVieS007** [comment]
This is fixed with version 1.9.2-RELEASE.
The problem came from two sides. A syscall conflicted with another syscall if they are performed at the same time, therefore the whole product checked against memleaks, memory errors, bad mutexes and fixed.

The another side was a wrong argument passed as integer, which could be fixed easier.
We added more protection layers from 1.9.2-RELEASE against memory errors, this release should be considered as very stable.
